spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: user
    password: password

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml


  data:
    task:
      execution:
        pool:
          core-size: 5
          max-size: 10
          queue-capacity: 25
    redis:
      port: 6379
      host: localhost
      life-time-minutes: 120
      retry:
        max-attempts: 5
        backoff: 1000
      channels:
        achievement: achievement_channel
        follower: follower_channel
        project: project_channel


  kafka:
    bootstrap-servers: localhost:9092
    pool-size: 3
    consumer:
      group-id: "group"
      auto-offset-reset: earliest
    topics:
      follower:
        name: follower_topic
        num-partitions: 3
        replication-factor: 1
      album-created:
        name: album-created_topic
        num-partitions: 3
        replication-factor: 1
      achievement:
        name: achievement_topic
        num-partitions: 3
        replication-factor: 1

server:
  name: Achievement Service
  main-thread-pool-size: 6
  port: 8085

logging:
  level:
    root: info

project-service:
  host: localhost
  port: 8082
