spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: user
    password: password

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml

  data:
    redis:
      port: 6379
      host: localhost
      channels:
        achievement: achievement_channel
        follower: follower_channel
        mentorshipStartEvent: mentorship_start_event_channel

achievement:
  executor:
    threads:
      count: 5
  name:
    sensei: SENSEI
  points:
    sensei: 30

server:
  port: 8085

logging:
  level:
    root: info

project-service:
  host: localhost
  port: 8082
