spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: user
    password: password

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml

  data:
    redis:
      port: 6379
      host: localhost
      channel:
        mentorship-channel:
          name: mentorship_channel
        achievement-channel:
          name: achievement_channel
        follower-channel:
          name: follower_channel
        like-channel:
          name: like_channel

achievements:
  mentorship-achievement:
    SENSEI:
      name: SENSEI
  like-achievements:
    ALL_LOVE:
      name: ALL LOVE

retryable:
  max-attempts: 5
  delay: 5000


task-executor:
  core-pool-size: 10
  max-pool-size: 20
  queue_capacity: 1000

server:
  port: 8085

logging:
  level:
    root: info

project-service:
  host: localhost
  port: 8082
