spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: user
    password: password

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml

  data:
    redis:
      port: 6379
      host: localhost
      channels:
        achievement-service:
          achievement-event:
            name: achievement_event_channel
        post-service:
          post-event:
            name: post_event_channel


server:
  port: 8085

logging:
  level:
    root: info

project-service:
  host: localhost
  port: 8082
